/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        white: 'var(--card-background)',
        canvas: 'var(--bg-canvas)',
        card: 'var(--card-background)',
        'forest-dark': 'var(--brand-forest-dark)',
        'forest-medium': 'var(--brand-forest-medium)',
        'forest-light': 'var(--brand-forest-light)',
        lime: {
          DEFAULT: 'var(--brand-lime)',
          hover: 'var(--brand-lime-hover)',
          soft: 'var(--brand-lime-translucent)',
        },
        main: 'var(--text-main)',
        'muted-green': 'var(--text-muted-green)',
        placeholder: 'var(--text-placeholder)',
        'white-soft': 'var(--border-dark-green)',
        'sidebar-muted': 'var(--text-sidebar-muted)',
        'sys-green': 'var(--sys-green)',
        'sys-green-bg': 'var(--sys-green-bg)',
        'sys-red': 'var(--sys-red)',
        'sys-red-bg': 'var(--sys-red-bg)',
        'sys-red-hover': 'var(--sys-red-hover)',
        'sys-orange': 'var(--sys-orange)',
        'sys-orange-bg': 'var(--sys-orange-bg)',
        promo: 'var(--bg-promo)',
        'surface-muted': 'var(--surface-muted)',
        'surface-hover': 'var(--surface-hover)',
        ink: 'var(--ink)',
        'badge-success': 'var(--badge-success-bg)',
        'badge-pending': 'var(--badge-pending-bg)',
        'badge-failed': 'var(--badge-failed-bg)',
        'table-hover': 'var(--table-row-hover)',
        overlay: 'var(--overlay)',
        navbar: 'var(--bg-navbar)',
        'sidebar-hover': 'var(--sidebar-link-hover)',
        'sidebar-active': 'var(--sidebar-link-active)',
      },
      borderColor: {
        light: 'var(--border-light)',
        'dark-green': 'var(--border-dark-green)',
        input: 'var(--border-input)',
        subtle: 'var(--border-subtle)',
        table: 'var(--border-table)',
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
      },
      borderRadius: {
        xxl: 'var(--radius-xxl)',
        xl: 'var(--radius-xl)',
        lg: 'var(--radius-lg)',
        md: 'var(--radius-md)',
        sm: 'var(--radius-sm)',
      },
      boxShadow: {
        'spark-sm': 'var(--shadow-spark-sm)',
        'spark-md': 'var(--shadow-spark-md)',
        'spark-lg': 'var(--shadow-spark-lg)',
        focus: '0 0 0 3px var(--ring-focus)',
        'focus-strong': '0 0 0 3px var(--ring-focus-strong)',
        'focus-danger': '0 0 0 3px var(--ring-danger)',
        'focus-success': '0 0 0 3px var(--ring-success)',
      },
      width: {
        sidebar: 'var(--sidebar-width)',
        'sidebar-collapsed': 'var(--sidebar-width-collapsed)',
        drawer: 'var(--drawer-width)',
      },
      spacing: {
        sidebar: 'var(--sidebar-width)',
        'sidebar-collapsed': 'var(--sidebar-width-collapsed)',
        navbar: 'var(--navbar-height)',
      },
      height: {
        navbar: 'var(--navbar-height)',
      },
      transitionTimingFunction: {
        drawer: 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
    },
  },
  plugins: [],
};
