/**
 * @param {string} category
 * @param {string} title
 * @param {string} brand
 * @param {number} price
 * @param {number} stock
 * @param {number} discountPercent
 * @param {string[]} tags
 * @param {Record<string, string>} attributes
 * @param {string} description
 */
function item(
  category,
  title,
  brand,
  price,
  stock,
  discountPercent,
  tags,
  attributes,
  description,
) {
  return {
    category,
    title,
    brand,
    price,
    stock,
    discountPercent,
    tags,
    attributes,
    description,
  };
}

export const SEED_CATEGORIES = [
  {
    name: 'Laptops',
    image: 'https://placehold.co/600x400/png?text=Laptops',
  },
  {
    name: 'Mobiles',
    image: 'https://placehold.co/600x400/png?text=Mobiles',
  },
  {
    name: 'Audio',
    image: 'https://placehold.co/600x400/png?text=Audio',
  },
  {
    name: "Men's Fashion",
    image: 'https://placehold.co/600x400/png?text=Mens+Fashion',
  },
  {
    name: "Women's Fashion",
    image: 'https://placehold.co/600x400/png?text=Womens+Fashion',
  },
  {
    name: 'Home & Kitchen',
    image: 'https://placehold.co/600x400/png?text=Home+Kitchen',
  },
];

export const SEED_PRODUCTS = [
  item(
    'Laptops',
    'Dell Inspiron 15 Laptop',
    'Dell',
    5499900,
    12,
    10,
    ['laptop', 'windows', 'student'],
    {
      color: 'Platinum Silver',
      ram: '16 GB',
      storage: '512 GB SSD',
      specs: 'Intel Core i5, 15.6 inch FHD',
    },
    'Everyday Windows laptop with a full-size keyboard and all-day battery.',
  ),
  item(
    'Laptops',
    'Lenovo IdeaPad Slim 3 Laptop',
    'Lenovo',
    4299900,
    20,
    12,
    ['laptop', 'windows', 'lightweight'],
    {
      color: 'Arctic Grey',
      ram: '8 GB',
      storage: '512 GB SSD',
      specs: 'AMD Ryzen 5, 14 inch',
    },
    'Thin Windows laptop for classes, browsing, and office work.',
  ),
  item(
    'Laptops',
    'ASUS VivoBook 16 Laptop',
    'ASUS',
    5899900,
    8,
    8,
    ['laptop', 'windows'],
    {
      color: 'Indie Black',
      ram: '16 GB',
      storage: '512 GB SSD',
      specs: 'Intel Core i5, 16 inch',
    },
    'Large-screen Windows laptop suited to spreadsheets and streaming.',
  ),
  item(
    'Laptops',
    'Acer Aspire 5 Laptop',
    'Acer',
    4799900,
    15,
    15,
    ['laptop', 'windows', 'student'],
    {
      color: 'Steel Gray',
      ram: '8 GB',
      storage: '512 GB SSD',
      specs: 'Intel Core i5, 15.6 inch',
    },
    'Practical Windows laptop with room for documents and photos.',
  ),
  item(
    'Laptops',
    'realme Book Slim Laptop',
    'realme',
    3999900,
    10,
    18,
    ['laptop', 'windows', 'lightweight'],
    {
      color: 'Real Blue',
      ram: '8 GB',
      storage: '256 GB SSD',
      specs: 'Intel Core i3, 14 inch',
    },
    'Compact Windows laptop for notes, video calls, and light multitasking.',
  ),
  item(
    'Laptops',
    'Honor MagicBook X 14 Laptop',
    'Honor',
    4499900,
    6,
    10,
    ['laptop', 'windows'],
    {
      color: 'Space Gray',
      ram: '8 GB',
      storage: '512 GB SSD',
      specs: 'Intel Core i5, 14 inch',
    },
    'Slim metal Windows laptop that is easy to carry between home and work.',
  ),
  item(
    'Laptops',
    'HP Pavilion 14 Laptop',
    'HP',
    6299900,
    9,
    5,
    ['laptop', 'windows'],
    {
      color: 'Natural Silver',
      ram: '16 GB',
      storage: '512 GB SSD',
      specs: 'Intel Core i5, 14 inch',
    },
    'Premium everyday Windows laptop with a bright display.',
  ),
  item(
    'Laptops',
    'Apple MacBook Air 13 Laptop',
    'Apple',
    9999900,
    5,
    0,
    ['laptop', 'macos'],
    {
      color: 'Midnight',
      ram: '8 GB',
      storage: '256 GB SSD',
      specs: 'Apple M2, 13.6 inch',
    },
    'Fanless macOS laptop for writing, photo edits, and travel.',
  ),
  item(
    'Laptops',
    'MSI Modern 15 Laptop',
    'MSI',
    7499900,
    4,
    8,
    ['laptop', 'windows', 'creator'],
    {
      color: 'Classic Black',
      ram: '16 GB',
      storage: '1 TB SSD',
      specs: 'Intel Core i7, 15.6 inch',
    },
    'Windows laptop with extra storage for design files and video.',
  ),
  item(
    'Laptops',
    'Samsung Galaxy Book4 Laptop',
    'Samsung',
    6999900,
    7,
    6,
    ['laptop', 'windows'],
    {
      color: 'Gray',
      ram: '16 GB',
      storage: '512 GB SSD',
      specs: 'Intel Core i5, 15.6 inch',
    },
    'Light Windows laptop that pairs with Galaxy phones.',
  ),
  item(
    'Mobiles',
    'Samsung Galaxy S24',
    'Samsung',
    7999900,
    14,
    5,
    ['phone', 'android', '5g'],
    {
      color: 'Onyx Black',
      ram: '8 GB',
      storage: '256 GB',
      specs: '6.2 inch AMOLED, 50 MP',
    },
    'Compact Android phone with a bright display and five years of updates.',
  ),
  item(
    'Mobiles',
    'Apple iPhone 15',
    'Apple',
    7299900,
    11,
    0,
    ['phone', 'ios', '5g'],
    {
      color: 'Blue',
      ram: '6 GB',
      storage: '128 GB',
      specs: '6.1 inch, 48 MP camera',
    },
    'Everyday iPhone with USB-C and a capable main camera.',
  ),
  item(
    'Mobiles',
    'Google Pixel 8a',
    'Google',
    4499900,
    16,
    10,
    ['phone', 'android', '5g'],
    {
      color: 'Bay',
      ram: '8 GB',
      storage: '128 GB',
      specs: '6.1 inch OLED, Tensor G3',
    },
    'Android phone known for clean software and dependable photos.',
  ),
  item(
    'Mobiles',
    'OnePlus 12R',
    'OnePlus',
    3999900,
    13,
    12,
    ['phone', 'android', '5g'],
    {
      color: 'Cool Blue',
      ram: '8 GB',
      storage: '128 GB',
      specs: '6.78 inch, 100W charging',
    },
    'Fast-charging Android phone with a smooth high-refresh display.',
  ),
  item(
    'Mobiles',
    'Xiaomi Redmi Note 13 Pro',
    'Xiaomi',
    2499900,
    22,
    15,
    ['phone', 'android', '5g'],
    {
      color: 'Midnight Black',
      ram: '8 GB',
      storage: '128 GB',
      specs: '200 MP camera, 6.67 inch',
    },
    'Midrange Android phone with a large camera sensor.',
  ),
  item(
    'Mobiles',
    'vivo V40',
    'vivo',
    3499900,
    9,
    8,
    ['phone', 'android', '5g'],
    {
      color: 'Lotus Purple',
      ram: '8 GB',
      storage: '128 GB',
      specs: '6.67 inch AMOLED',
    },
    'Slim Android phone with a bright screen for photos and video.',
  ),
  item(
    'Mobiles',
    'Motorola Edge 50',
    'Motorola',
    2799900,
    18,
    10,
    ['phone', 'android', '5g'],
    {
      color: 'Jungle Green',
      ram: '8 GB',
      storage: '256 GB',
      specs: '6.7 inch pOLED',
    },
    'Light Android phone with a stock-like interface.',
  ),
  item(
    'Mobiles',
    'Nothing Phone 2a',
    'Nothing',
    2399900,
    12,
    5,
    ['phone', 'android', '5g'],
    {
      color: 'White',
      ram: '8 GB',
      storage: '128 GB',
      specs: '6.7 inch, Glyph lights',
    },
    'Distinctive Android phone with a transparent back and clean software.',
  ),
  item(
    'Mobiles',
    'OPPO Reno 11',
    'OPPO',
    2999900,
    10,
    12,
    ['phone', 'android', '5g'],
    {
      color: 'Rock Grey',
      ram: '8 GB',
      storage: '128 GB',
      specs: '6.7 inch AMOLED',
    },
    'Portrait-focused Android phone with a curved display.',
  ),
  item(
    'Mobiles',
    'realme Narzo 70',
    'realme',
    1599900,
    0,
    20,
    ['phone', 'android', '5g'],
    {
      color: 'Forest Green',
      ram: '6 GB',
      storage: '128 GB',
      specs: '6.67 inch, 50 MP',
    },
    'Budget Android phone. Currently out of stock.',
  ),
  item(
    'Audio',
    'Sony WH-1000XM5 Headphones',
    'Sony',
    2999900,
    8,
    10,
    ['headphones', 'wireless', 'noise-cancelling'],
    { color: 'Black', specs: 'Over-ear, 30 hour battery' },
    'Wireless over-ear headphones with strong noise cancelling for travel.',
  ),
  item(
    'Audio',
    'Bose QuietComfort Ultra Headphones',
    'Bose',
    3499900,
    6,
    0,
    ['headphones', 'wireless', 'noise-cancelling'],
    { color: 'White Smoke', specs: 'Over-ear, spatial audio' },
    'Plush wireless headphones built for long flights and offices.',
  ),
  item(
    'Audio',
    'JBL Tune 770NC Headphones',
    'JBL',
    699900,
    25,
    15,
    ['headphones', 'wireless'],
    { color: 'Blue', specs: 'Over-ear, 44 hour battery' },
    'Affordable wireless headphones with long battery life.',
  ),
  item(
    'Audio',
    'boAt Airdopes 141 Earbuds',
    'boAt',
    129900,
    40,
    25,
    ['earbuds', 'wireless'],
    { color: 'Black', specs: '42 hour total playback' },
    'Everyday wireless earbuds with a charging case.',
  ),
  item(
    'Audio',
    'Samsung Galaxy Buds FE',
    'Samsung',
    799900,
    14,
    10,
    ['earbuds', 'wireless'],
    { color: 'Graphite', specs: 'Active noise cancelling' },
    'Compact wireless earbuds that fit Galaxy phones.',
  ),
  item(
    'Audio',
    'Sennheiser HD 450SE Headphones',
    'Sennheiser',
    999900,
    7,
    12,
    ['headphones', 'wireless'],
    { color: 'Black', specs: 'Over-ear, aptX' },
    'Wireless headphones with a balanced sound for music and calls.',
  ),
  item(
    'Audio',
    'Marshall Emberton II Speaker',
    'Marshall',
    1499900,
    11,
    5,
    ['speaker', 'wireless', 'portable'],
    { color: 'Cream', specs: 'IP67, 30 hour battery' },
    'Portable Bluetooth speaker with a compact brick shape.',
  ),
  item(
    'Audio',
    'JBL Flip 6 Speaker',
    'JBL',
    999900,
    19,
    8,
    ['speaker', 'wireless', 'portable'],
    { color: 'Teal', specs: 'IP67, 12 hour battery' },
    'Rugged portable speaker for rooms and short trips.',
  ),
  item(
    'Audio',
    'Sony SRS-XB100 Speaker',
    'Sony',
    499900,
    21,
    10,
    ['speaker', 'wireless', 'portable'],
    { color: 'Blue', specs: '16 hour battery' },
    'Small Bluetooth speaker that clips onto a bag.',
  ),
  item(
    'Audio',
    'Apple AirPods 4',
    'Apple',
    1799900,
    9,
    0,
    ['earbuds', 'wireless'],
    { color: 'White', specs: 'USB-C case' },
    'Open-fit wireless earbuds for iPhone and iPad.',
  ),
  item(
    "Men's Fashion",
    'Peter England Slim Fit Shirt',
    'Peter England',
    149900,
    30,
    20,
    ['shirt', 'formal', 'cotton'],
    { color: 'White', size: 'M', specs: 'Cotton, full sleeves' },
    'Crisp cotton shirt for office wear.',
  ),
  item(
    "Men's Fashion",
    'Allen Solly Oxford Shirt',
    'Allen Solly',
    179900,
    18,
    15,
    ['shirt', 'casual', 'cotton'],
    { color: 'Sky Blue', size: 'L', specs: 'Oxford cotton' },
    'Button-down oxford shirt for smart casual outfits.',
  ),
  item(
    "Men's Fashion",
    "Levi's 511 Slim Jeans",
    "Levi's",
    299900,
    16,
    10,
    ['jeans', 'denim'],
    { color: 'Dark Indigo', size: '32', specs: 'Slim stretch denim' },
    'Slim jeans with a bit of stretch for daily wear.',
  ),
  item(
    "Men's Fashion",
    'US Polo Assn Polo T-Shirt',
    'US Polo Assn',
    129900,
    28,
    18,
    ['t-shirt', 'casual'],
    { color: 'Navy', size: 'M', specs: 'Pique cotton' },
    'Classic polo for weekends and warm afternoons.',
  ),
  item(
    "Men's Fashion",
    'Raymond Cotton Trousers',
    'Raymond',
    219900,
    12,
    12,
    ['trousers', 'formal'],
    { color: 'Charcoal', size: '34', specs: 'Flat front cotton' },
    'Tailored trousers that pair with formal shirts.',
  ),
  item(
    "Men's Fashion",
    'Van Heusen Formal Shirt',
    'Van Heusen',
    169900,
    20,
    10,
    ['shirt', 'formal'],
    { color: 'Light Blue', size: 'L', specs: 'Easy-iron cotton' },
    'Formal shirt cut for a neat office silhouette.',
  ),
  item(
    "Men's Fashion",
    'Puma Running Shoes',
    'Puma',
    349900,
    14,
    15,
    ['shoes', 'sports'],
    { color: 'Black', size: '8', specs: 'Mesh upper, cushioned sole' },
    'Lightweight running shoes for daily jogs and gym sessions.',
  ),
  item(
    "Men's Fashion",
    'Adidas Essentials Hoodie',
    'Adidas',
    279900,
    11,
    8,
    ['hoodie', 'casual'],
    { color: 'Grey', size: 'L', specs: 'Fleece, kangaroo pocket' },
    'Soft hoodie for travel and cooler evenings.',
  ),
  item(
    "Men's Fashion",
    'Woodland Leather Belt',
    'Woodland',
    99900,
    24,
    5,
    ['belt', 'leather'],
    { color: 'Brown', size: '36', specs: 'Full grain leather' },
    'Brown leather belt with a simple buckle.',
  ),
  item(
    "Men's Fashion",
    'Manyavar Kurta Set',
    'Manyavar',
    399900,
    8,
    20,
    ['kurta', 'festive'],
    { color: 'Maroon', size: 'M', specs: 'Silk blend, churidar included' },
    'Festive kurta set for weddings and celebrations.',
  ),
  item(
    "Women's Fashion",
    'Biba Anarkali Kurta',
    'Biba',
    249900,
    15,
    18,
    ['kurta', 'festive'],
    { color: 'Teal', size: 'M', specs: 'Printed cotton, calf length' },
    'Flared kurta with a festive print.',
  ),
  item(
    "Women's Fashion",
    'W for Woman Cotton Kurta',
    'W for Woman',
    189900,
    17,
    12,
    ['kurta', 'cotton'],
    { color: 'Mustard', size: 'L', specs: 'Straight cotton' },
    'Straight cotton kurta for everyday wear.',
  ),
  item(
    "Women's Fashion",
    "Levi's 721 High Rise Jeans",
    "Levi's",
    329900,
    10,
    10,
    ['jeans', 'denim'],
    { color: 'Black', size: '28', specs: 'High rise skinny' },
    'High-rise jeans with a close fit.',
  ),
  item(
    "Women's Fashion",
    'H&M Ribbed Top',
    'H&M',
    79900,
    26,
    5,
    ['top', 'casual'],
    { color: 'Black', size: 'S', specs: 'Ribbed jersey' },
    'Short-sleeve ribbed top that layers easily.',
  ),
  item(
    "Women's Fashion",
    'Libas Straight Kurta',
    'Libas',
    159900,
    19,
    20,
    ['kurta', 'cotton'],
    { color: 'Pink', size: 'M', specs: 'Cotton, side slits' },
    'Light cotton kurta for warm days.',
  ),
  item(
    "Women's Fashion",
    'Bata Ballet Flats',
    'Bata',
    129900,
    13,
    8,
    ['shoes', 'flats'],
    { color: 'Nude', size: '6', specs: 'Cushioned insole' },
    'Simple ballet flats for office and errands.',
  ),
  item(
    "Women's Fashion",
    'Zara Linen Shirt',
    'Zara',
    229900,
    9,
    0,
    ['shirt', 'linen'],
    { color: 'White', size: 'M', specs: 'Linen blend' },
    'Relaxed linen shirt for warm weather.',
  ),
  item(
    "Women's Fashion",
    'Aurelia Palazzo Set',
    'Aurelia',
    219900,
    12,
    15,
    ['kurta', 'palazzo'],
    { color: 'Green', size: 'L', specs: 'Kurta with palazzo' },
    'Coordinated kurta and palazzo set.',
  ),
  item(
    "Women's Fashion",
    'Nike Revolution 7 Shoes',
    'Nike',
    399900,
    8,
    10,
    ['shoes', 'sports'],
    { color: 'White', size: '6', specs: 'Mesh running shoe' },
    'Cushioned running shoes for walks and workouts.',
  ),
  item(
    "Women's Fashion",
    'Fabindia Cotton Dupatta',
    'Fabindia',
    149900,
    14,
    5,
    ['dupatta', 'cotton'],
    { color: 'Indigo', size: 'Free', specs: 'Handwoven cotton' },
    'Handwoven cotton dupatta to wear with kurtas.',
  ),
  item(
    'Home & Kitchen',
    'Prestige Deluxe Cooker 5L',
    'Prestige',
    249900,
    18,
    10,
    ['cooker', 'kitchen'],
    { color: 'Silver', specs: '5 litre, aluminium' },
    'Family-size pressure cooker for rice and dals.',
  ),
  item(
    'Home & Kitchen',
    'Bajaj Majesty Oven 19L',
    'Bajaj',
    599900,
    7,
    12,
    ['oven', 'kitchen'],
    { color: 'Black', specs: '19 litre OTG' },
    'Compact oven for baking and grilling small batches.',
  ),
  item(
    'Home & Kitchen',
    'Philips Daily Mixer 750W',
    'Philips',
    349900,
    11,
    8,
    ['mixer', 'kitchen'],
    { color: 'White', specs: '750W, 3 jars' },
    'Mixer grinder for batters, chutneys, and dry spices.',
  ),
  item(
    'Home & Kitchen',
    'Hawkins Contura Cooker 3L',
    'Hawkins',
    199900,
    16,
    5,
    ['cooker', 'kitchen'],
    { color: 'Black', specs: '3 litre, hard anodised' },
    'Hard-anodised pressure cooker for smaller households.',
  ),
  item(
    'Home & Kitchen',
    'Pigeon Favourite Pan',
    'Pigeon',
    89900,
    22,
    15,
    ['pan', 'kitchen'],
    { color: 'Red', specs: 'Non-stick, 240 mm' },
    'Non-stick frying pan for eggs, dosas, and stir fries.',
  ),
  item(
    'Home & Kitchen',
    'Milton Thermosteel Bottle 1L',
    'Milton',
    99900,
    30,
    10,
    ['bottle', 'kitchen'],
    { color: 'Steel', specs: '1 litre, 24 hour hot' },
    'Steel flask that keeps water hot or cold through the day.',
  ),
  item(
    'Home & Kitchen',
    'Cello Prima Casserole',
    'Cello',
    69900,
    20,
    8,
    ['casserole', 'kitchen'],
    { color: 'Blue', specs: '1500 ml insulated' },
    'Insulated casserole for serving dal and sabzi.',
  ),
  item(
    'Home & Kitchen',
    'Borosil Glass Mixing Bowl',
    'Borosil',
    49900,
    25,
    0,
    ['bowl', 'kitchen'],
    { color: 'Clear', specs: '1.5 litre borosilicate' },
    'Glass mixing bowl that is safe for the microwave.',
  ),
  item(
    'Home & Kitchen',
    'AGARO Imperial Kettle',
    'AGARO',
    129900,
    13,
    12,
    ['kettle', 'kitchen'],
    { color: 'Black', specs: '1.8 litre, stainless steel' },
    'Electric kettle for tea and instant noodles.',
  ),
  item(
    'Home & Kitchen',
    'Butterfly Rapid Pressure Cooker',
    'Butterfly',
    179900,
    9,
    10,
    ['cooker', 'kitchen'],
    { color: 'Silver', specs: '3 litre, induction base' },
    'Induction-ready pressure cooker for weekday meals.',
  ),
];
